namespace: 'loyalty'
fullnameOverride: 'event-worker'

ingress:
  enabled: false

doppler:
  secretCRDName: dopplersecret-event-worker-prod
  secretTokenName: doppler-event-worker-prod-token-secret
  secretServiceName: doppler-event-worker-prod-secret

envDeployment:
  DOTNET_ENVIRONMENT: Production
  DD_LOGS_INJECTION: "true"
  N1coPaymentsService__IdUrl: "https://id-payments.n1co.com"
  N1coPaymentsService__Url: "https://api-payments.n1co.com"
  Onboarding__Reward: 500
  AuthenticationService__Authority: "https://id.n1co.shop"
  AuthenticationService__Audience: "https://n1co.pay.prod"
  LoyaltyCore__LoyaltyProgramIntegrationId: "n1co-loyalty"
  LoyaltyCore__CampaignIntegrationIds__PlayGame: "n1co-roulette"
  LoyaltyCore__Service__Url: "https://n1-loyalty-core-prod-cus.azurewebsites.net"
  CashBack__Service__Url: "https://issuing-api.n1co.com"

deployment:
  containerPort: 8080
  livenessProbeEnabled: false
  readinessProbeEnabled: false

service:
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 600Mi
  requests:
    cpu: 400m
    memory: 500Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  node-purpose: worker

podAnnotations:
  ad.datadoghq.com/event-worker.logs: '[{"source": "csharp"}]'
  admission.datadoghq.com/dotnet-lib.version: v2.47.0

datadogLabels:
  env: "production"
  service: 'loyalty-event-worker'
  admissionEnabled: "true"